
services:
  # db:
  #   image: postgres:15
  #   env_file:
  #     - ./placement-portal-backend/.env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    # volumes:
    #   - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    # depends_on:
    #   - db

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  #     - frontend
  #     - db

# volumes:
#   postgres_data:
